$(document).ready(function(){
	// This part builds the menu from the autogenerated list
	$('#megamenu').append('<div id="hiddenmenu"><ul><li></li></ul><img src=""https://cdn2.bigcommerce.com/n-arxsrf/p1qyb/product_images/uploaded_images/whitepixel.jpg""></div>');
	$('#hiddenmenu').attr("display","inline");
	$('#hiddenmenu').hide();
	//This part shows the menu (and selects the right image) on mouseover
	$('#megamenu > ul > li').mouseover(function() {
		// This code selects the image for each category.  The image should be named using the first 4 letters of the category + "-menu.jpg"
		var imgName = $(this).children('a').html().substr(0,4).toLowerCase();
		var imgName = imgName.replace(" ","");
		if (imgName != "") {
			$('#hiddenmenu > img').attr('src',"https://cdn2.bigcommerce.com/n-arxsrf/p1qyb/product_images/uploaded_images/" + imgName + "-menu.jpg");
		}
		var content = $(this).children('ul').html();
		$('#hiddenmenu ul').html(content);
		$('#hiddenmenu').show();
	});
	//This part hides the menu on mouseout
	$('#megamenu').mouseleave(function(){
		$('#hiddenmenu').hide();
	})

});
